name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: moreworld/filebin:latest

      - name: deploying on digitalocean
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://ferryhandy.com/api/server/restart'
          timeout: 20000
          method: 'GET'
          customHeaders: '{"key": "${{ secrets.FERRYHANDY_KEY }}"}'

